name: m_taksi
description: M-Taxi ilovasi
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  flutter_svg: ^2.2.0
  provider: ^6.1.1
  dio: ^5.3.2
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  # image_picker: ^0.8.7+4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    # - assets/default_avatar.png
    # - assets/svgs/

  fonts:
    - family: Hauora
      fonts:
        - asset: assets/fonts/Hauora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Hauora-Light.ttf
          weight: 300
        - asset: assets/fonts/Hauora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Hauora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Hauora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Hauora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Hauora-ExtraBold.ttf
          weight: 800

# Platformaga xos konfiguratsiyalar (flutter bo'limidan tashqarida)
android:
  package: com.example.m_taksi
  versionCode: 1
  versionName: "1.0.0"
  compileSdkVersion: 34
  minSdkVersion: 21
  targetSdkVersion: 34

ios:
  bundleIdentifier: com.example.mTaksi
  minimumOsVersion: "13.0"
  usesSwift: true